services:
    db:
      image: postgres:16 
      container_name: imgfetchr-db
      environment: 
        POSTGRES_USER: ${DB_USER}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        POSTGRES_DB: ${DB_NAME}
      ports:
        - "5433:5432"
      volumes:
        - db_data:/var/lib/postgresql/data
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
        interval: 10s
        timeout: 5s
        retries: 5
      
    migrate:
        image: migrate/migrate:4
        volumes:
          - ./migrations:/migrations
        entrypoint: 
        - migrate
        - -path=/migrations
        - -database=postgres://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}?sslmode=disable
        depends_on:
          - db
volumes:
  db_data: