version: "3.9"
services:
    db:
      image: postgres:16 
      container_name: imgfetchr-db
      environment: 
        POSTGRES_USER: ${DB_USER}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        POSTGRES_DB: ${DB_NAME}
      ports:
        - "5432:5432"
      volumes:
        - db_data:/var/lib/postgresql/data
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres -d imgfetchr"]
        interval: 10s
        timeout: 5s
        retries: 5

volumes:
  db_data: